# Generated by Django 3.1.4 on 2023-10-17 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Casas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alquiler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.CharField(max_length=20)),
                ('casaalquiler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Casas.casas')),
                ('personaalquiler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Casas.personas')),
            ],
        ),
    ]
